GET http://localhost:3000/api/posts

###


POST http://localhost:3000/api/posts HTTP/1.1
content-type: application/json

{
         
            "title": "Typescript",
            "content": "Ijson-server --watch db.json",
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Typescript_logo_2020.svg/1200px-Typescript_logo_2020.svg.png",
            "authorId": 1,
            "tags": ["json-server","ojuhoh bjbb", "backend", "rest", "api"],
            "likeCounter": 0
}